@startuml
left to right direction
title MediZano - Casos de uso generales
actor Cajero
actor "Encargado de almacen" as Almacen
actor "Atencion al cliente" as Soporte
actor "Gerente / Analista" as Gerente
actor Administrador
rectangle "Botica POS MediZano" {
  usecase "Autenticar usuario" as G1
  usecase "Registrar venta" as G2
  usecase "Gestionar medicamentos" as G3
  usecase "Controlar inventario" as G4
  usecase "Procesar devolucion" as G5
  usecase "Consultar reportes" as G6
  usecase "Administrar usuarios" as G7
}
Cajero --> G1
Cajero --> G2
Almacen --> G3
Almacen --> G4
Soporte --> G5
Gerente --> G6
Administrador --> G7
@enduml
