@startuml
title Botica POS MediZano - Objetos
object "cajero01: Usuario" as Cajero { username = "cajero"; rol = CAJERO }
object "paracetamol: Medicamento" as Med { nombre = "Paracetamol 500 mg"; precioVenta = 2.50 }
object "lote001: Lote" as Lote { codigo = "L-2026-01"; stockActual = 120 }
object "venta001: Venta" as Venta { numero = "V-0001"; subtotal = 21.19; igv = 3.81; total = 25.00; estado = PAGADA }
object "detalle001: DetalleVenta" as Detalle { cantidad = 10; importe = 25.00 }
object "pago001: Pago" as Pago { metodo = EFECTIVO; montoPagado = 30.00; vuelto = 5.00 }
object "boleta001: Comprobante" as Comp { serie = "B001"; numero = "000001" }
Cajero --> Venta
Venta --> Detalle
Detalle --> Med
Detalle --> Lote
Venta --> Pago
Venta --> Comp
@enduml
