@startuml
title Botica POS MediZano - Comunicacion
object Cajero
object "Frontend Angular" as FE
object "API REST" as API
object "Servicio Ventas" as Ventas
object "Servicio Inventario" as Inventario
object "Servicio Reportes" as Reportes
object "PostgreSQL" as DB
object "PDF" as PDF
Cajero -> FE : 1. pide operacion
FE -> API : 2. envia request con JWT
API -> Ventas : 3. procesa venta
Ventas -> Inventario : 4. verifica stock
Inventario -> DB : 5. consulta lote
DB --> Inventario : 6. retorna existencias
Inventario --> Ventas : 7. confirma disponibilidad
Ventas -> DB : 8. registra venta
Ventas -> PDF : 9. genera comprobante
Ventas -> Reportes : 10. actualiza indicadores
@enduml
